[build]
  publish = "buildco"
  functions = "buildco/netlify/functions"

[functions]
  node_bundler = "esbuild"

[site]
  domain = "buildcoprojects.netlify.app"

[[redirects]]
  from = "/success"
  to = "/payment-success.html"
  status = 200

[[redirects]]
  from = "/cancelled"
  to = "/payment-cancelled.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = {page = ["404*"]}}
